import type { DemoLocale } from 'src/constants/builder'

export type StreamLabels = ReturnType<typeof getLabels>

const zh = {
  addField: '添加字段',
  aggregate: '聚合',
  apply: '应用',
  cancel: '取消',
  chartType: '图表类型',
  collapse: '收起',
  config: '配置',
  dimensions: '维度',
  dropHere: '放到这里',
  emptyChart: '拖入字段开始分析',
  encodings: '编码映射',
  expandAll: '展开全部',
  facet: '分面',
  filters: '筛选器',
  filterValue: '值',
  fullscreen: '全屏',
  exitFullscreen: '退出全屏',
  language: '语言',
  languageChinese: '中',
  languageEnglish: 'EN',
  limit: '限制',
  initializing: '正在初始化...',
  metrics: '指标',
  max: '最大值',
  min: '最小值',
  noValueRequired: '无需输入值',
  operator: '操作符',
  rawDate: '原始',
  removeField: '移除字段',
  search: '搜索指标 & 字段',
  settings: '设置',
  source: '数据源',
  theme: '主题',
  themeDark: '深色',
  themeLight: '浅色',
  loading: '正在渲染图表...',
  rowCount: '行',
  havingFilter: '聚合筛选',
  whereFilter: '行筛选',
}

const en: typeof zh = {
  addField: 'Add field',
  aggregate: 'Aggregate',
  apply: 'Apply',
  cancel: 'Cancel',
  chartType: 'Chart type',
  collapse: 'Collapse',
  config: 'Config',
  dimensions: 'Dimensions',
  dropHere: 'Drop here',
  emptyChart: 'Drop fields to start',
  encodings: 'Encodings',
  expandAll: 'Expand all',
  facet: 'Facet',
  filters: 'Filters',
  filterValue: 'Value',
  fullscreen: 'Fullscreen',
  exitFullscreen: 'Exit fullscreen',
  language: 'Language',
  languageChinese: '中',
  languageEnglish: 'EN',
  limit: 'Limit',
  initializing: 'Initializing...',
  metrics: 'Metrics',
  max: 'Max',
  min: 'Min',
  noValueRequired: 'No value required',
  operator: 'Operator',
  rawDate: 'Raw',
  removeField: 'Remove field',
  search: 'Search metrics & fields',
  settings: 'Settings',
  source: 'Source',
  theme: 'Theme',
  themeDark: 'Dark',
  themeLight: 'Light',
  loading: 'Rendering chart...',
  rowCount: 'rows',
  havingFilter: 'Having Filter',
  whereFilter: 'Where Filter',
}

export const getLabels = (locale: DemoLocale | undefined) =>
  ({
    ...(locale === 'en-US' ? en : zh),
    locale: locale === 'en-US' ? 'en-US' : 'zh-CN',
  }) as const
