import type { ThemeConfig } from 'antd';
import type { VbiThemePalette } from './palette';

type GlobalTokens = NonNullable<ThemeConfig['token']>;

export const createVbiAntdGlobalTokens = (
  p: VbiThemePalette,
): GlobalTokens => ({
  colorBgBase: p.bgSolid,
  colorBgContainer: p.surfaceSolid,
  colorBgContainerDisabled: p.controlMuted,
  colorBgElevated: p.surfaceSolid,
  colorBgLayout: p.bgSolid,
  colorBgTextActive: p.activeBg,
  colorBgTextHover: p.hoverBg,
  colorBorder: p.border,
  colorBorderBg: p.surfaceSolid,
  colorBorderSecondary: p.rowBorder,
  colorError: p.danger,
  colorErrorActive: p.danger,
  colorErrorBorder: p.danger,
  colorErrorBorderHover: p.danger,
  colorErrorHover: p.danger,
  colorErrorText: p.danger,
  colorErrorTextActive: p.danger,
  colorErrorTextHover: p.danger,
  colorFill: p.activeBg,
  colorFillAlter: p.tableHead,
  colorFillContent: p.controlMuted,
  colorFillContentHover: p.hoverBg,
  colorFillQuaternary: p.surfaceSoft,
  colorFillSecondary: p.activeBg,
  colorFillTertiary: p.controlMuted,
  colorInfo: p.primary,
  colorInfoActive: p.primaryHover,
  colorInfoBorder: p.primary,
  colorInfoBorderHover: p.primaryHover,
  colorInfoHover: p.primaryHover,
  colorInfoText: p.primary,
  colorInfoTextActive: p.primaryHover,
  colorInfoTextHover: p.primaryHover,
  colorLink: p.activeText,
  colorLinkActive: p.activeText,
  colorLinkHover: p.activeText,
  colorPrimary: p.primary,
  colorPrimaryActive: p.primaryHover,
  colorPrimaryBg: p.primary,
  colorPrimaryBgHover: p.primaryHover,
  colorPrimaryBorder: p.primary,
  colorPrimaryBorderHover: p.primaryHover,
  colorPrimaryHover: p.primaryHover,
  colorPrimaryText: p.primary,
  colorPrimaryTextActive: p.primaryHover,
  colorPrimaryTextHover: p.primaryHover,
  colorSplit: p.rowBorder,
  colorText: p.text,
  colorTextBase: p.text,
  colorTextDescription: p.textMuted,
  colorTextDisabled: p.textSoft,
  colorTextHeading: p.textStrong,
  colorTextLabel: p.textMuted,
  colorTextPlaceholder: p.placeholder,
  colorTextQuaternary: p.textSoft,
  colorTextSecondary: p.textMuted,
  colorTextTertiary: p.textSoft,
  borderRadius: 8,
  controlHeight: 32,
  boxShadow: p.shadow,
});
