export const howToUseVbiBuilderContent = `# How to use VBI Builder

## Runtime
Call the vbi_builder tool with JavaScript code. Globals inside the script:
- \`workspace\` - injected Builder workspace
- \`chart\` - chart workspace slot
- \`report\` - report workspace slot
- \`json(value)\` - returns value as the script result
- \`assert(cond, msg)\` - throws on false
- \`console\` - logs captured into the tool result

Open the builder from the injected slot. If the CLI was started with \`--chart-id\`, \`chart.open()\` uses that chart. Otherwise list resources with \`vbi_resource\` and pass the id to \`chart.open(id)\`:
\`\`\`js
const b = await chart.open('chart-id');
b.chartType.changeChartType('bar');
b.dimensions.add('region', n => n.setEncoding('yAxis'));
b.measures.add('sales', n => n.setEncoding('xAxis').setAggregate({ func: 'sum' }));
return json({ dsl: b.build() });
\`\`\`

## Chart Builder
Top-level: \`chartType\`, \`dimensions\`, \`measures\`, \`whereFilter\`, \`havingFilter\`, \`theme\`, \`locale\`, \`limit\`, \`undoManager\`, \`build()\`, \`buildVQuery()\`, \`buildVSeed(options?)\`, \`isEmpty()\`, \`getSchema()\`.

Chart types include table, pivotTable, column, columnParallel, columnPercent, line, area, areaPercent, bar, barParallel, barPercent, pie, donut, scatter, heatmap, sunburst, treeMap, funnel, boxplot, histogram, radar, rose, dualAxis, and race charts.

Dimensions:
- \`add(field, node => ...)\`, \`remove(id)\`, \`update(id, cb)\`, \`find(p)\`, \`findAll()\`, \`toJSON()\`
- Node setters: \`setAlias(name)\`, \`setEncoding(value)\`, \`setSort({order})\`, \`setAggregate({func})\`, \`clearSort()\`, \`clearAggregate()\`, \`getId()\`
- Common encodings: xAxis, yAxis, color, detail, tooltip, label, row, column, hierarchy, angle, player

Measures:
- \`add(field, node => ...)\`, \`remove(id)\`, \`update(id, cb)\`, \`find(p)\`, \`findAll()\`, \`toJSON()\`
- Node setters: \`setAlias(name)\`, \`setEncoding(value)\`, \`setAggregate({func, quantile?})\`, \`setFormat(format)\`, \`setSort({order})\`, \`clearSort()\`, \`clearFormat()\`, \`getId()\`
- Aggregate funcs: sum, count, countDistinct, avg, min, max, variance, variancePop, stddev, median, quantile

Filters:
- \`whereFilter\` filters raw rows before aggregation.
- \`havingFilter\` filters grouped values after aggregation and should set aggregate metadata.
- Common operators: ==, !=, <, >, <=, >=, contains, startsWith, in, between.

## Report Builder
Open with \`const r = await report.open('report-id')\`, or omit the id when the CLI was started with \`--report-id\`.

Common operations:
- \`r.page.add(title, page => page.setChartId(chartBuilderOrId))\`
- \`r.page.add(title, page => page.setInsightId(insightBuilderOrId))\`
- \`r.page.remove(pageId)\`, \`r.page.update(pageId, cb)\`, \`r.page.get(pageId)\`
- \`r.build()\`, \`r.isEmpty()\`

## Gotchas
- Builder callbacks mutate synchronously.
- Switching chart type can remap invalid encodings.
- \`buildVSeed()\` is async and can be expensive; prefer \`build()\` for inspection.
- IDs are generated by the builder. Use \`getId()\` from nodes when updating or removing later.
`
