import {
  translateVBIComponentText,
  type VBIComponentText,
  type VBIComponentTextResolver,
  type VBIComponentTextSource,
} from '../localization'

export type VBIChartEditorText = VBIComponentText
export type VBIChartEditorTranslate = VBIComponentTextResolver
export type VBIChartEditorTextSource = VBIComponentTextSource

export type VBIChartEditorTextKey =
  | 'toolbarChartTypePanelTitle'
  | 'toolbarChartTypeFallbackDescription'
  | 'toolbarChartTypeEmpty'
  | 'toolbarChartTypeGroupsTableLabel'
  | 'toolbarChartTypeGroupsTableDescription'
  | 'toolbarChartTypeGroupsComparisonLabel'
  | 'toolbarChartTypeGroupsComparisonDescription'
  | 'toolbarChartTypeGroupsTrendLabel'
  | 'toolbarChartTypeGroupsTrendDescription'
  | 'toolbarChartTypeGroupsProportionLabel'
  | 'toolbarChartTypeGroupsProportionDescription'
  | 'toolbarChartTypeGroupsDistributionLabel'
  | 'toolbarChartTypeGroupsDistributionDescription'
  | 'toolbarChartTypeGroupsHierarchyLabel'
  | 'toolbarChartTypeGroupsHierarchyDescription'
  | 'toolbarChartTypeGroupsDynamicLabel'
  | 'toolbarChartTypeGroupsDynamicDescription'
  | 'toolbarChartTypeItemsTableLabel'
  | 'toolbarChartTypeItemsTableDescription'
  | 'toolbarChartTypeItemsPivotTableLabel'
  | 'toolbarChartTypeItemsPivotTableDescription'
  | 'toolbarChartTypeItemsColumnLabel'
  | 'toolbarChartTypeItemsColumnDescription'
  | 'toolbarChartTypeItemsColumnParallelLabel'
  | 'toolbarChartTypeItemsColumnParallelDescription'
  | 'toolbarChartTypeItemsColumnPercentLabel'
  | 'toolbarChartTypeItemsColumnPercentDescription'
  | 'toolbarChartTypeItemsBarLabel'
  | 'toolbarChartTypeItemsBarDescription'
  | 'toolbarChartTypeItemsBarParallelLabel'
  | 'toolbarChartTypeItemsBarParallelDescription'
  | 'toolbarChartTypeItemsBarPercentLabel'
  | 'toolbarChartTypeItemsBarPercentDescription'
  | 'toolbarChartTypeItemsDualAxisLabel'
  | 'toolbarChartTypeItemsDualAxisDescription'
  | 'toolbarChartTypeItemsLineLabel'
  | 'toolbarChartTypeItemsLineDescription'
  | 'toolbarChartTypeItemsAreaLabel'
  | 'toolbarChartTypeItemsAreaDescription'
  | 'toolbarChartTypeItemsAreaPercentLabel'
  | 'toolbarChartTypeItemsAreaPercentDescription'
  | 'toolbarChartTypeItemsPieLabel'
  | 'toolbarChartTypeItemsPieDescription'
  | 'toolbarChartTypeItemsDonutLabel'
  | 'toolbarChartTypeItemsDonutDescription'
  | 'toolbarChartTypeItemsRoseLabel'
  | 'toolbarChartTypeItemsRoseDescription'
  | 'toolbarChartTypeItemsRoseParallelLabel'
  | 'toolbarChartTypeItemsRoseParallelDescription'
  | 'toolbarChartTypeItemsFunnelLabel'
  | 'toolbarChartTypeItemsFunnelDescription'
  | 'toolbarChartTypeItemsScatterLabel'
  | 'toolbarChartTypeItemsScatterDescription'
  | 'toolbarChartTypeItemsHeatmapLabel'
  | 'toolbarChartTypeItemsHeatmapDescription'
  | 'toolbarChartTypeItemsRadarLabel'
  | 'toolbarChartTypeItemsRadarDescription'
  | 'toolbarChartTypeItemsTreeMapLabel'
  | 'toolbarChartTypeItemsTreeMapDescription'
  | 'toolbarChartTypeItemsSunburstLabel'
  | 'toolbarChartTypeItemsSunburstDescription'
  | 'toolbarChartTypeItemsCirclePackingLabel'
  | 'toolbarChartTypeItemsCirclePackingDescription'
  | 'toolbarChartTypeItemsSankeyLabel'
  | 'toolbarChartTypeItemsSankeyDescription'
  | 'toolbarChartTypeItemsHierarchySankeyLabel'
  | 'toolbarChartTypeItemsHierarchySankeyDescription'
  | 'toolbarChartTypeItemsRaceBarLabel'
  | 'toolbarChartTypeItemsRaceBarDescription'
  | 'toolbarChartTypeItemsRaceColumnLabel'
  | 'toolbarChartTypeItemsRaceColumnDescription'
  | 'toolbarChartTypeItemsRaceLineLabel'
  | 'toolbarChartTypeItemsRaceLineDescription'
  | 'toolbarChartTypeItemsRaceScatterLabel'
  | 'toolbarChartTypeItemsRaceScatterDescription'
  | 'toolbarChartTypeItemsRacePieLabel'
  | 'toolbarChartTypeItemsRacePieDescription'
  | 'toolbarChartTypeItemsRaceDonutLabel'
  | 'toolbarChartTypeItemsRaceDonutDescription'
  | 'toolbarHistoryUndo'
  | 'toolbarHistoryRedo'
  | 'toolbarHistoryLabel'
  | 'toolbarLimitLabel'
  | 'toolbarLimitTooltip'
  | 'toolbarThemeLabel'
  | 'toolbarThemeDescription'
  | 'toolbarThemeLight'
  | 'toolbarThemeDark'

export const translateVBIChartEditorText = translateVBIComponentText
