import type { ProfessionalLocale } from 'src/constants/builder'

const zh = {
  addField: '添加字段',
  chartType: '图表类型',
  config: '配置',
  configPanel: '配置面板',
  dataSource: '数据字段',
  dimensions: '维度',
  dragHint: '拖到匹配的编码槽，蓝色插入线表示落点',
  dropHere: '拖到这里',
  dropUnavailable: '类型不匹配',
  emptyChart: '拖入字段开始配置图表',
  exitFullscreen: '退出全屏',
  fieldCollapse: '收起',
  fieldExpand: '展开全部',
  formatCnyWan: '¥符号(万)',
  formatNumber2: '数值 (2)',
  formatPercent1: '百分比 (1)',
  formatScientific3: '科学计数 (3)',
  formatUsdK: '$K (2)',
  fullscreen: '全屏',
  insertAt: '插入位置',
  languageChinese: '中',
  languageEnglish: 'EN',
  limit: '行数',
  loading: '正在渲染...',
  menuAggregate: '聚合',
  menuAutoFormat: '自动格式',
  menuDelete: '删除',
  menuFormat: '格式',
  menuRaw: '原始值',
  menuRename: '重命名',
  menuSort: '排序',
  menuSortAsc: '升序',
  menuSortClear: '不排序',
  menuSortDesc: '降序',
  metrics: '指标',
  search: '搜索字段',
  themeDark: '深色',
  themeLight: '浅色',
  toolbarRedo: '重做',
  toolbarUndo: '撤销',
  unmatchedFields: '未匹配字段',
}

const en: typeof zh = {
  addField: 'Add field',
  chartType: 'Chart type',
  config: 'Config',
  configPanel: 'Config panel',
  dataSource: 'Fields',
  dimensions: 'Dimensions',
  dragHint: 'Drop on a matching encoding slot. The blue line marks the index.',
  dropHere: 'Drop here',
  dropUnavailable: 'Wrong field type',
  emptyChart: 'Drop fields to configure the chart',
  exitFullscreen: 'Exit fullscreen',
  fieldCollapse: 'Collapse',
  fieldExpand: 'Expand all',
  formatCnyWan: '¥Symbol(万)',
  formatNumber2: 'Number (2)',
  formatPercent1: 'Percent (1)',
  formatScientific3: 'Scientific (3)',
  formatUsdK: '$K (2)',
  fullscreen: 'Fullscreen',
  insertAt: 'Insert at',
  languageChinese: '中',
  languageEnglish: 'EN',
  limit: 'Rows',
  loading: 'Rendering...',
  menuAggregate: 'Aggregate',
  menuAutoFormat: 'Auto format',
  menuDelete: 'Delete',
  menuFormat: 'Format',
  menuRaw: 'Raw',
  menuRename: 'Rename',
  menuSort: 'Sort',
  menuSortAsc: 'Asc',
  menuSortClear: 'No sort',
  menuSortDesc: 'Desc',
  metrics: 'Metrics',
  search: 'Search fields',
  themeDark: 'Dark',
  themeLight: 'Light',
  toolbarRedo: 'Redo',
  toolbarUndo: 'Undo',
  unmatchedFields: 'Unmatched fields',
}

export type ProfessionalLabels = ReturnType<typeof getLabels>

export const getLabels = (locale: ProfessionalLocale) => ({
  ...(locale === 'en-US' ? en : zh),
  locale,
})
