/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ThemeConfig } from "./components/ui/vbi-config-provider/theme";
import { VBIChartBuilder } from "@visactor/vbi";
import { VBIStoreApi } from "./store/vbi-store";
import { IconDefinition } from "@ant-design/icons-svg/lib/types";
export { ThemeConfig } from "./components/ui/vbi-config-provider/theme";
export { VBIChartBuilder } from "@visactor/vbi";
export { VBIStoreApi } from "./store/vbi-store";
export { IconDefinition } from "@ant-design/icons-svg/lib/types";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VbiButton {
        /**
          * Active state (pressed/selected)
          * @default false
         */
        "active": boolean;
        /**
          * Main color (primary, secondary, accent, etc.)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Shape (square, circle, wide, block)
         */
        "shape"?: 'square' | 'circle' | 'wide' | 'block';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the button
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant (ghost, outline, dash, soft, link)
         */
        "variant"?: 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
    }
    interface VbiConfigProvider {
        /**
          * VBI chart builder instance to initialize the store with
         */
        "builder"?: VBIChartBuilder;
        /**
          * Returns the VBI store instance for child components
         */
        "getStore": () => Promise<VBIStoreApi>;
        /**
          * Theme configuration containing mode ('light' | 'dark') and design tokens
         */
        "theme"?: ThemeConfig;
    }
    interface VbiIcon {
        /**
          * The color of the icon. Defaults to 'currentColor'.
          * @default 'currentColor'
         */
        "color": string;
        /**
          * The icon definition object from `@ant-design/icons-svg`.
         */
        "icon": IconDefinition;
        /**
          * The size of the icon (e.g., '16px', '1em', '2rem').
          * @default '1em'
         */
        "size": string;
    }
    interface VbiInput {
        /**
          * Autocomplete hint for the browser
         */
        "autocomplete"?: string;
        /**
          * Auto-focus the input on mount
          * @default false
         */
        "autofocus": boolean;
        /**
          * Primary color (primary, secondary, info, error...)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Maximum character length
         */
        "maxlength"?: number;
        /**
          * Minimum character length
         */
        "minlength"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Placeholder text
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Read-only state (focusable but not editable)
          * @default false
         */
        "readOnly": boolean;
        /**
          * Required field for form validation
          * @default false
         */
        "required": boolean;
        /**
          * Size of the input
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the input element (text, password, email, number, date...)
          * @default 'text'
         */
        "type": string;
        /**
          * Value of the input element
          * @default ''
         */
        "value"?: string;
        /**
          * Display variant (e.g., ghost - transparent)
         */
        "variant"?: 'ghost';
    }
    interface VbiJoin {
        /**
          * Vertical orientation
          * @default false
         */
        "vertical": boolean;
    }
}
export interface VbiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiInputElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVbiButtonElement extends Components.VbiButton, HTMLStencilElement {
    }
    var HTMLVbiButtonElement: {
        prototype: HTMLVbiButtonElement;
        new (): HTMLVbiButtonElement;
    };
    interface HTMLVbiConfigProviderElement extends Components.VbiConfigProvider, HTMLStencilElement {
    }
    var HTMLVbiConfigProviderElement: {
        prototype: HTMLVbiConfigProviderElement;
        new (): HTMLVbiConfigProviderElement;
    };
    interface HTMLVbiIconElement extends Components.VbiIcon, HTMLStencilElement {
    }
    var HTMLVbiIconElement: {
        prototype: HTMLVbiIconElement;
        new (): HTMLVbiIconElement;
    };
    interface HTMLVbiInputElementEventMap {
        "vbiInput": string;
        "vbiChange": string;
        "vbiFocus": void;
        "vbiBlur": void;
    }
    interface HTMLVbiInputElement extends Components.VbiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiInputElementEventMap>(type: K, listener: (this: HTMLVbiInputElement, ev: VbiInputCustomEvent<HTMLVbiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiInputElementEventMap>(type: K, listener: (this: HTMLVbiInputElement, ev: VbiInputCustomEvent<HTMLVbiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiInputElement: {
        prototype: HTMLVbiInputElement;
        new (): HTMLVbiInputElement;
    };
    interface HTMLVbiJoinElement extends Components.VbiJoin, HTMLStencilElement {
    }
    var HTMLVbiJoinElement: {
        prototype: HTMLVbiJoinElement;
        new (): HTMLVbiJoinElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "vbi-button": HTMLVbiButtonElement;
        "vbi-config-provider": HTMLVbiConfigProviderElement;
        "vbi-icon": HTMLVbiIconElement;
        "vbi-input": HTMLVbiInputElement;
        "vbi-join": HTMLVbiJoinElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VbiButton {
        /**
          * Active state (pressed/selected)
          * @default false
         */
        "active"?: boolean;
        /**
          * Main color (primary, secondary, accent, etc.)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Shape (square, circle, wide, block)
         */
        "shape"?: 'square' | 'circle' | 'wide' | 'block';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the button
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant (ghost, outline, dash, soft, link)
         */
        "variant"?: 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
    }
    interface VbiConfigProvider {
        /**
          * VBI chart builder instance to initialize the store with
         */
        "builder"?: VBIChartBuilder;
        /**
          * Theme configuration containing mode ('light' | 'dark') and design tokens
         */
        "theme"?: ThemeConfig;
    }
    interface VbiIcon {
        /**
          * The color of the icon. Defaults to 'currentColor'.
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * The icon definition object from `@ant-design/icons-svg`.
         */
        "icon"?: IconDefinition;
        /**
          * The size of the icon (e.g., '16px', '1em', '2rem').
          * @default '1em'
         */
        "size"?: string;
    }
    interface VbiInput {
        /**
          * Autocomplete hint for the browser
         */
        "autocomplete"?: string;
        /**
          * Auto-focus the input on mount
          * @default false
         */
        "autofocus"?: boolean;
        /**
          * Primary color (primary, secondary, info, error...)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Maximum character length
         */
        "maxlength"?: number;
        /**
          * Minimum character length
         */
        "minlength"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Event emitted when the input loses focus (blur)
         */
        "onVbiBlur"?: (event: VbiInputCustomEvent<void>) => void;
        /**
          * Event emitted when the user finishes typing and blurs (or presses Enter)
         */
        "onVbiChange"?: (event: VbiInputCustomEvent<string>) => void;
        /**
          * Event emitted when the input gains focus
         */
        "onVbiFocus"?: (event: VbiInputCustomEvent<void>) => void;
        /**
          * Event emitted when the user types
         */
        "onVbiInput"?: (event: VbiInputCustomEvent<string>) => void;
        /**
          * Placeholder text
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Read-only state (focusable but not editable)
          * @default false
         */
        "readOnly"?: boolean;
        /**
          * Required field for form validation
          * @default false
         */
        "required"?: boolean;
        /**
          * Size of the input
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the input element (text, password, email, number, date...)
          * @default 'text'
         */
        "type"?: string;
        /**
          * Value of the input element
          * @default ''
         */
        "value"?: string;
        /**
          * Display variant (e.g., ghost - transparent)
         */
        "variant"?: 'ghost';
    }
    interface VbiJoin {
        /**
          * Vertical orientation
          * @default false
         */
        "vertical"?: boolean;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface VbiButtonAttributes {
        "type": 'button' | 'submit' | 'reset';
        "color": 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        "variant": 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "shape": 'square' | 'circle' | 'wide' | 'block';
        "disabled": boolean;
        "active": boolean;
    }
    interface VbiIconAttributes {
        "size": string;
        "color": string;
    }
    interface VbiInputAttributes {
        "type": string;
        "value": string;
        "placeholder": string;
        "disabled": boolean;
        "name": string;
        "readOnly": boolean;
        "required": boolean;
        "maxlength": number;
        "minlength": number;
        "autocomplete": string;
        "autofocus": boolean;
        "color": 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        "variant": 'ghost';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiJoinAttributes {
        "vertical": boolean;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "vbi-button": Omit<VbiButton, keyof VbiButtonAttributes> & { [K in keyof VbiButton & keyof VbiButtonAttributes]?: VbiButton[K] } & { [K in keyof VbiButton & keyof VbiButtonAttributes as `attr:${K}`]?: VbiButtonAttributes[K] } & { [K in keyof VbiButton & keyof VbiButtonAttributes as `prop:${K}`]?: VbiButton[K] };
        "vbi-config-provider": VbiConfigProvider;
        "vbi-icon": Omit<VbiIcon, keyof VbiIconAttributes> & { [K in keyof VbiIcon & keyof VbiIconAttributes]?: VbiIcon[K] } & { [K in keyof VbiIcon & keyof VbiIconAttributes as `attr:${K}`]?: VbiIconAttributes[K] } & { [K in keyof VbiIcon & keyof VbiIconAttributes as `prop:${K}`]?: VbiIcon[K] };
        "vbi-input": Omit<VbiInput, keyof VbiInputAttributes> & { [K in keyof VbiInput & keyof VbiInputAttributes]?: VbiInput[K] } & { [K in keyof VbiInput & keyof VbiInputAttributes as `attr:${K}`]?: VbiInputAttributes[K] } & { [K in keyof VbiInput & keyof VbiInputAttributes as `prop:${K}`]?: VbiInput[K] };
        "vbi-join": Omit<VbiJoin, keyof VbiJoinAttributes> & { [K in keyof VbiJoin & keyof VbiJoinAttributes]?: VbiJoin[K] } & { [K in keyof VbiJoin & keyof VbiJoinAttributes as `attr:${K}`]?: VbiJoinAttributes[K] } & { [K in keyof VbiJoin & keyof VbiJoinAttributes as `prop:${K}`]?: VbiJoin[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "vbi-button": LocalJSX.IntrinsicElements["vbi-button"] & JSXBase.HTMLAttributes<HTMLVbiButtonElement>;
            "vbi-config-provider": LocalJSX.IntrinsicElements["vbi-config-provider"] & JSXBase.HTMLAttributes<HTMLVbiConfigProviderElement>;
            "vbi-icon": LocalJSX.IntrinsicElements["vbi-icon"] & JSXBase.HTMLAttributes<HTMLVbiIconElement>;
            "vbi-input": LocalJSX.IntrinsicElements["vbi-input"] & JSXBase.HTMLAttributes<HTMLVbiInputElement>;
            "vbi-join": LocalJSX.IntrinsicElements["vbi-join"] & JSXBase.HTMLAttributes<HTMLVbiJoinElement>;
        }
    }
}
