/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ThemeConfig } from "./components/ui/vbi-config-provider/theme";
import { VBIChartBuilder } from "@visactor/vbi";
import { VBIStoreApi } from "./store/vbi-store";
export { ThemeConfig } from "./components/ui/vbi-config-provider/theme";
export { VBIChartBuilder } from "@visactor/vbi";
export { VBIStoreApi } from "./store/vbi-store";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VbiButton {
        /**
          * Active state (pressed/selected)
          * @default false
         */
        "active": boolean;
        /**
          * Main color (primary, secondary, accent, etc.)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Shape (square, circle, wide, block)
         */
        "shape"?: 'square' | 'circle' | 'wide' | 'block';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the button
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant (ghost, outline, dash, soft, link)
         */
        "variant"?: 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
    }
    interface VbiConfigProvider {
        /**
          * VBI chart builder instance to initialize the store with
         */
        "builder"?: VBIChartBuilder;
        /**
          * Returns the VBI store instance for child components
         */
        "getStore": () => Promise<VBIStoreApi>;
        /**
          * Theme configuration containing mode ('light' | 'dark') and design tokens
         */
        "theme"?: ThemeConfig;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVbiButtonElement extends Components.VbiButton, HTMLStencilElement {
    }
    var HTMLVbiButtonElement: {
        prototype: HTMLVbiButtonElement;
        new (): HTMLVbiButtonElement;
    };
    interface HTMLVbiConfigProviderElement extends Components.VbiConfigProvider, HTMLStencilElement {
    }
    var HTMLVbiConfigProviderElement: {
        prototype: HTMLVbiConfigProviderElement;
        new (): HTMLVbiConfigProviderElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "vbi-button": HTMLVbiButtonElement;
        "vbi-config-provider": HTMLVbiConfigProviderElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VbiButton {
        /**
          * Active state (pressed/selected)
          * @default false
         */
        "active"?: boolean;
        /**
          * Main color (primary, secondary, accent, etc.)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Shape (square, circle, wide, block)
         */
        "shape"?: 'square' | 'circle' | 'wide' | 'block';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the button
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant (ghost, outline, dash, soft, link)
         */
        "variant"?: 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
    }
    interface VbiConfigProvider {
        /**
          * VBI chart builder instance to initialize the store with
         */
        "builder"?: VBIChartBuilder;
        /**
          * Theme configuration containing mode ('light' | 'dark') and design tokens
         */
        "theme"?: ThemeConfig;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface VbiButtonAttributes {
        "type": 'button' | 'submit' | 'reset';
        "color": 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        "variant": 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "shape": 'square' | 'circle' | 'wide' | 'block';
        "disabled": boolean;
        "active": boolean;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "vbi-button": Omit<VbiButton, keyof VbiButtonAttributes> & { [K in keyof VbiButton & keyof VbiButtonAttributes]?: VbiButton[K] } & { [K in keyof VbiButton & keyof VbiButtonAttributes as `attr:${K}`]?: VbiButtonAttributes[K] } & { [K in keyof VbiButton & keyof VbiButtonAttributes as `prop:${K}`]?: VbiButton[K] };
        "vbi-config-provider": VbiConfigProvider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "vbi-button": LocalJSX.IntrinsicElements["vbi-button"] & JSXBase.HTMLAttributes<HTMLVbiButtonElement>;
            "vbi-config-provider": LocalJSX.IntrinsicElements["vbi-config-provider"] & JSXBase.HTMLAttributes<HTMLVbiConfigProviderElement>;
        }
    }
}
