/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CascadingMenuItem } from "./components/ui/vbi-cascading-menu/vbi-cascading-menu";
import { FieldRole } from "./utils/data/fieldRole";
import { VBISchemaField } from "./store/chart/schema-fields";
import { HavingFilterLike } from "./components/chart/shelves/vbi-chart-having/helpers/having-utils";
import { VSeed } from "@visactor/vseed";
import { WhereFilterLike } from "./components/chart/shelves/vbi-chart-where/helpers/where-utils";
import { ThemeConfig } from "./components/ui/vbi-config-provider/theme";
import { VBIChartBuilder } from "@visactor/vbi";
import { DropdownPlacement } from "./components/ui/vbi-dropdown/vbi-dropdown";
import { IconDefinition } from "@ant-design/icons-svg/lib/types";
import { MenuItem } from "./components/ui/vbi-menu/vbi-menu";
import { SelectOption } from "./components/ui/vbi-select/vbi-select";
import { TabItem } from "./components/ui/vbi-tab/vbi-tab";
import { TooltipPosition } from "./components/ui/vbi-tooltip/vbi-tooltip";
export { CascadingMenuItem } from "./components/ui/vbi-cascading-menu/vbi-cascading-menu";
export { FieldRole } from "./utils/data/fieldRole";
export { VBISchemaField } from "./store/chart/schema-fields";
export { HavingFilterLike } from "./components/chart/shelves/vbi-chart-having/helpers/having-utils";
export { VSeed } from "@visactor/vseed";
export { WhereFilterLike } from "./components/chart/shelves/vbi-chart-where/helpers/where-utils";
export { ThemeConfig } from "./components/ui/vbi-config-provider/theme";
export { VBIChartBuilder } from "@visactor/vbi";
export { DropdownPlacement } from "./components/ui/vbi-dropdown/vbi-dropdown";
export { IconDefinition } from "@ant-design/icons-svg/lib/types";
export { MenuItem } from "./components/ui/vbi-menu/vbi-menu";
export { SelectOption } from "./components/ui/vbi-select/vbi-select";
export { TabItem } from "./components/ui/vbi-tab/vbi-tab";
export { TooltipPosition } from "./components/ui/vbi-tooltip/vbi-tooltip";
export namespace Components {
    interface VbiButton {
        /**
          * Active state (pressed/selected)
          * @default false
         */
        "active": boolean;
        /**
          * Main color (primary, secondary, accent, etc.)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Shape (square, circle, wide, block)
         */
        "shape"?: 'square' | 'circle' | 'wide' | 'block';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the button
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant (ghost, outline, dash, soft, link)
         */
        "variant"?: 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
    }
    interface VbiCascadingMenu {
        /**
          * Array of menu items to be rendered
          * @default []
         */
        "items": CascadingMenuItem[];
        /**
          * The size of the menu. Defaults to 'md'
          * @default 'md'
         */
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * The orientation variant of the menu. Defaults to 'vertical'
          * @default 'vertical'
         */
        "variant": 'horizontal' | 'vertical';
    }
    interface VbiChartDimension {
    }
    interface VbiChartEditor {
    }
    interface VbiChartFieldFilter {
        /**
          * The current search keyword.
          * @default ''
         */
        "keyword": string;
        /**
          * The currently selected field roles.
          * @default []
         */
        "selectedRoles": FieldRole[];
        /**
          * The currently selected field types.
          * @default []
         */
        "selectedTypes": string[];
    }
    interface VbiChartFieldSection {
        /**
          * The list of dimensions to display.
          * @default []
         */
        "dimensions": VBISchemaField[];
        /**
          * The list of measures to display.
          * @default []
         */
        "measures": VBISchemaField[];
    }
    interface VbiChartFields {
    }
    interface VbiChartHaving {
    }
    interface VbiChartHavingFilter {
        /**
          * @default {}
         */
        "fieldRoleMap"?: Record<string, string>;
        /**
          * @default {}
         */
        "fieldTypeMap": Record<string, string>;
        "item": HavingFilterLike;
    }
    interface VbiChartMeasure {
    }
    interface VbiChartRender {
        /**
          * The VSeed configuration object used to render the chart or table.
         */
        "vseed"?: VSeed;
    }
    interface VbiChartShelfPanel {
    }
    interface VbiChartToolbar {
    }
    interface VbiChartType {
    }
    interface VbiChartUpload {
        /**
          * Prefix for generated local CSV connector IDs.
          * @default 'local_csv'
         */
        "connectorIdPrefix": string;
    }
    interface VbiChartWhere {
    }
    interface VbiChartWhereFilter {
        /**
          * @default {}
         */
        "fieldRoleMap"?: Record<string, string>;
        /**
          * @default {}
         */
        "fieldTypeMap": Record<string, string>;
        "item": WhereFilterLike;
    }
    interface VbiCheckbox {
        /**
          * Whether the component is checked.
          * @default false
         */
        "checked": boolean;
        /**
          * The theme color of the component.
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Whether the component is disabled.
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether the checkbox is in an indeterminate state.
          * @default false
         */
        "indeterminate": boolean;
        /**
          * The name of the component, used for form submission.
          * @default ''
         */
        "name": string;
        /**
          * The size of the component.
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiConfigProvider {
        /**
          * VBI chart builder instance to initialize the store with
         */
        "builder"?: VBIChartBuilder;
        /**
          * Theme configuration containing mode ('light' | 'dark') and design tokens
         */
        "theme"?: ThemeConfig;
    }
    interface VbiDropdown {
        /**
          * When true, the dropdown cannot be opened.
          * @default false
         */
        "disabled": boolean;
        /**
          * The distance between the dropdown and its trigger (in pixels).
          * @default 8
         */
        "offset": number;
        /**
          * Controls the open state of the dropdown.
          * @default false
         */
        "open": boolean;
        /**
          * The position of the dropdown relative to its trigger.
          * @default 'bottom'
         */
        "placement"?: DropdownPlacement;
        /**
          * The interaction mode of the popover ('auto' closes on outside click, 'manual' does not).
          * @default 'auto'
         */
        "popoverMode": 'auto' | 'manual';
        /**
          * How the dropdown is triggered.
          * @default 'click'
         */
        "trigger": 'click' | 'hover';
    }
    interface VbiIcon {
        /**
          * The color of the icon. Defaults to 'currentColor'.
          * @default 'currentColor'
         */
        "color": string;
        /**
          * The icon definition object from `@ant-design/icons-svg`.
         */
        "icon"?: IconDefinition;
        /**
          * The size of the icon (unitless, scaled relative to --size-base).
          * @default 16
         */
        "size": number;
    }
    interface VbiInput {
        /**
          * Autocomplete hint for the browser
         */
        "autocomplete"?: string;
        /**
          * Auto-focus the input on mount
          * @default false
         */
        "autofocus": boolean;
        /**
          * Primary color (primary, secondary, info, error...)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Maximum value for number or date input
         */
        "max"?: number | string;
        /**
          * Maximum character length
         */
        "maxlength"?: number;
        /**
          * Minimum value for number or date input
         */
        "min"?: number | string;
        /**
          * Minimum character length
         */
        "minlength"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Placeholder text
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Read-only state (focusable but not editable)
          * @default false
         */
        "readOnly": boolean;
        /**
          * Required field for form validation
          * @default false
         */
        "required": boolean;
        /**
          * Size of the input
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Step for number input
         */
        "step"?: number | string;
        /**
          * Type of the input element (text, password, email, number, date...)
          * @default 'text'
         */
        "type": string;
        /**
          * Value of the input element
          * @default ''
         */
        "value"?: string | number;
        /**
          * Display variant (e.g., ghost - transparent)
         */
        "variant"?: 'ghost';
    }
    interface VbiJoin {
        /**
          * Vertical orientation
          * @default false
         */
        "vertical": boolean;
    }
    interface VbiLoading {
        /**
          * Primary color. If not provided, it inherits the parent element's text color (currentColor)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Loading style (spinner, dots, ring, ball, bars, infinity)
          * @default 'spinner'
         */
        "type": 'spinner' | 'dots' | 'ring' | 'ball' | 'bars' | 'infinity';
    }
    interface VbiMenu {
        /**
          * Array of menu items to be rendered
          * @default []
         */
        "items": MenuItem[];
        /**
          * The size of the menu. Defaults to 'md'
          * @default 'md'
         */
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * The orientation variant of the menu. Defaults to 'vertical'
          * @default 'vertical'
         */
        "variant": 'horizontal' | 'vertical';
    }
    interface VbiModal {
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'middle'
         */
        "position": 'top' | 'bottom' | 'middle' | 'start' | 'end';
    }
    interface VbiSelect {
        /**
          * Color variant of the select
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'success' | 'warning' | 'info' | 'error' | 'neutral' | 'ghost';
        /**
          * Whether the select is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * List of select options
         */
        "options"?: SelectOption[];
        /**
          * Placeholder text when no option is selected
         */
        "placeholder"?: string;
        /**
          * Size of the select
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Current value of the select
         */
        "value"?: string | number;
    }
    interface VbiSwitch {
        /**
          * Whether the switch is checked.
          * @default false
         */
        "checked": boolean;
        /**
          * The color theme of the switch.
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'success' | 'warning' | 'info' | 'error' | 'neutral';
        /**
          * Whether the switch is disabled.
          * @default false
         */
        "disabled": boolean;
        /**
          * The name of the component, used for form submission.
          * @default ''
         */
        "name": string;
        /**
          * The size of the switch.
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiTab {
        /**
          * Whether the tabs occupy the full width of their parent container
          * @default false
         */
        "block": boolean;
        /**
          * Whether all tabs are disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Array of tab items to be rendered
          * @default []
         */
        "items": TabItem[];
        /**
          * Size of the tabs
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Currently active tab value or ID
         */
        "value"?: string | number;
    }
    interface VbiTooltip {
        /**
          * The semantic color theme of the tooltip
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Delay in milliseconds before showing the tooltip on hover
          * @default 0
         */
        "enterDelay": number;
        /**
          * Delay in milliseconds before hiding the tooltip on leave
          * @default 0
         */
        "leaveDelay": number;
        /**
          * The distance between the tooltip and its trigger (in pixels)
          * @default 8
         */
        "offset": number;
        /**
          * Whether the tooltip is currently open/visible
          * @default false
         */
        "open": boolean;
        /**
          * The position of the tooltip relative to its target
          * @default 'top'
         */
        "position": TooltipPosition;
        /**
          * The text to display inside the tooltip
          * @default ''
         */
        "text": string;
        /**
          * How the tooltip is triggered ('hover', 'click', or 'manual')
          * @default 'hover'
         */
        "trigger": 'hover' | 'click' | 'manual';
    }
}
export interface VbiCascadingMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiCascadingMenuElement;
}
export interface VbiChartFieldFilterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiChartFieldFilterElement;
}
export interface VbiChartHavingFilterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiChartHavingFilterElement;
}
export interface VbiChartUploadCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiChartUploadElement;
}
export interface VbiChartWhereFilterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiChartWhereFilterElement;
}
export interface VbiCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiCheckboxElement;
}
export interface VbiConfigProviderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiConfigProviderElement;
}
export interface VbiDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiDropdownElement;
}
export interface VbiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiInputElement;
}
export interface VbiMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiMenuElement;
}
export interface VbiModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiModalElement;
}
export interface VbiSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiSelectElement;
}
export interface VbiSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiSwitchElement;
}
export interface VbiTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVbiTabElement;
}
declare global {
    interface HTMLVbiButtonElement extends Components.VbiButton, HTMLStencilElement {
    }
    var HTMLVbiButtonElement: {
        prototype: HTMLVbiButtonElement;
        new (): HTMLVbiButtonElement;
    };
    interface HTMLVbiCascadingMenuElementEventMap {
        "vbiCascadingMenuSelect": CascadingMenuItem;
    }
    interface HTMLVbiCascadingMenuElement extends Components.VbiCascadingMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiCascadingMenuElementEventMap>(type: K, listener: (this: HTMLVbiCascadingMenuElement, ev: VbiCascadingMenuCustomEvent<HTMLVbiCascadingMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiCascadingMenuElementEventMap>(type: K, listener: (this: HTMLVbiCascadingMenuElement, ev: VbiCascadingMenuCustomEvent<HTMLVbiCascadingMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiCascadingMenuElement: {
        prototype: HTMLVbiCascadingMenuElement;
        new (): HTMLVbiCascadingMenuElement;
    };
    interface HTMLVbiChartDimensionElement extends Components.VbiChartDimension, HTMLStencilElement {
    }
    var HTMLVbiChartDimensionElement: {
        prototype: HTMLVbiChartDimensionElement;
        new (): HTMLVbiChartDimensionElement;
    };
    interface HTMLVbiChartEditorElement extends Components.VbiChartEditor, HTMLStencilElement {
    }
    var HTMLVbiChartEditorElement: {
        prototype: HTMLVbiChartEditorElement;
        new (): HTMLVbiChartEditorElement;
    };
    interface HTMLVbiChartFieldFilterElementEventMap {
        "vbiChartFieldFilterRole": FieldRole[];
        "vbiChartFieldFilterType": string[];
        "vbiChartFieldFilterKeyword": string;
    }
    interface HTMLVbiChartFieldFilterElement extends Components.VbiChartFieldFilter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiChartFieldFilterElementEventMap>(type: K, listener: (this: HTMLVbiChartFieldFilterElement, ev: VbiChartFieldFilterCustomEvent<HTMLVbiChartFieldFilterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiChartFieldFilterElementEventMap>(type: K, listener: (this: HTMLVbiChartFieldFilterElement, ev: VbiChartFieldFilterCustomEvent<HTMLVbiChartFieldFilterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiChartFieldFilterElement: {
        prototype: HTMLVbiChartFieldFilterElement;
        new (): HTMLVbiChartFieldFilterElement;
    };
    interface HTMLVbiChartFieldSectionElement extends Components.VbiChartFieldSection, HTMLStencilElement {
    }
    var HTMLVbiChartFieldSectionElement: {
        prototype: HTMLVbiChartFieldSectionElement;
        new (): HTMLVbiChartFieldSectionElement;
    };
    interface HTMLVbiChartFieldsElement extends Components.VbiChartFields, HTMLStencilElement {
    }
    var HTMLVbiChartFieldsElement: {
        prototype: HTMLVbiChartFieldsElement;
        new (): HTMLVbiChartFieldsElement;
    };
    interface HTMLVbiChartHavingElement extends Components.VbiChartHaving, HTMLStencilElement {
    }
    var HTMLVbiChartHavingElement: {
        prototype: HTMLVbiChartHavingElement;
        new (): HTMLVbiChartHavingElement;
    };
    interface HTMLVbiChartHavingFilterElementEventMap {
        "vbiChartHavingFilterSave": { item: HavingFilterLike; event?: MouseEvent };
        "vbiChartHavingFilterCancel": MouseEvent | undefined;
    }
    interface HTMLVbiChartHavingFilterElement extends Components.VbiChartHavingFilter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiChartHavingFilterElementEventMap>(type: K, listener: (this: HTMLVbiChartHavingFilterElement, ev: VbiChartHavingFilterCustomEvent<HTMLVbiChartHavingFilterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiChartHavingFilterElementEventMap>(type: K, listener: (this: HTMLVbiChartHavingFilterElement, ev: VbiChartHavingFilterCustomEvent<HTMLVbiChartHavingFilterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiChartHavingFilterElement: {
        prototype: HTMLVbiChartHavingFilterElement;
        new (): HTMLVbiChartHavingFilterElement;
    };
    interface HTMLVbiChartMeasureElement extends Components.VbiChartMeasure, HTMLStencilElement {
    }
    var HTMLVbiChartMeasureElement: {
        prototype: HTMLVbiChartMeasureElement;
        new (): HTMLVbiChartMeasureElement;
    };
    interface HTMLVbiChartRenderElement extends Components.VbiChartRender, HTMLStencilElement {
    }
    var HTMLVbiChartRenderElement: {
        prototype: HTMLVbiChartRenderElement;
        new (): HTMLVbiChartRenderElement;
    };
    interface HTMLVbiChartShelfPanelElement extends Components.VbiChartShelfPanel, HTMLStencilElement {
    }
    var HTMLVbiChartShelfPanelElement: {
        prototype: HTMLVbiChartShelfPanelElement;
        new (): HTMLVbiChartShelfPanelElement;
    };
    interface HTMLVbiChartToolbarElement extends Components.VbiChartToolbar, HTMLStencilElement {
    }
    var HTMLVbiChartToolbarElement: {
        prototype: HTMLVbiChartToolbarElement;
        new (): HTMLVbiChartToolbarElement;
    };
    interface HTMLVbiChartTypeElement extends Components.VbiChartType, HTMLStencilElement {
    }
    var HTMLVbiChartTypeElement: {
        prototype: HTMLVbiChartTypeElement;
        new (): HTMLVbiChartTypeElement;
    };
    interface HTMLVbiChartUploadElementEventMap {
        "vbiChartUploadSuccess": {
    connectorId: string
    fileName: string
    rowCount: number
  };
    }
    interface HTMLVbiChartUploadElement extends Components.VbiChartUpload, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiChartUploadElementEventMap>(type: K, listener: (this: HTMLVbiChartUploadElement, ev: VbiChartUploadCustomEvent<HTMLVbiChartUploadElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiChartUploadElementEventMap>(type: K, listener: (this: HTMLVbiChartUploadElement, ev: VbiChartUploadCustomEvent<HTMLVbiChartUploadElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiChartUploadElement: {
        prototype: HTMLVbiChartUploadElement;
        new (): HTMLVbiChartUploadElement;
    };
    interface HTMLVbiChartWhereElement extends Components.VbiChartWhere, HTMLStencilElement {
    }
    var HTMLVbiChartWhereElement: {
        prototype: HTMLVbiChartWhereElement;
        new (): HTMLVbiChartWhereElement;
    };
    interface HTMLVbiChartWhereFilterElementEventMap {
        "vbiChartWhereFilterSave": { item: WhereFilterLike; event?: MouseEvent };
        "vbiChartWhereFilterCancel": MouseEvent | undefined;
    }
    interface HTMLVbiChartWhereFilterElement extends Components.VbiChartWhereFilter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiChartWhereFilterElementEventMap>(type: K, listener: (this: HTMLVbiChartWhereFilterElement, ev: VbiChartWhereFilterCustomEvent<HTMLVbiChartWhereFilterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiChartWhereFilterElementEventMap>(type: K, listener: (this: HTMLVbiChartWhereFilterElement, ev: VbiChartWhereFilterCustomEvent<HTMLVbiChartWhereFilterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiChartWhereFilterElement: {
        prototype: HTMLVbiChartWhereFilterElement;
        new (): HTMLVbiChartWhereFilterElement;
    };
    interface HTMLVbiCheckboxElementEventMap {
        "vbiCheckboxChange": boolean;
    }
    interface HTMLVbiCheckboxElement extends Components.VbiCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiCheckboxElementEventMap>(type: K, listener: (this: HTMLVbiCheckboxElement, ev: VbiCheckboxCustomEvent<HTMLVbiCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiCheckboxElementEventMap>(type: K, listener: (this: HTMLVbiCheckboxElement, ev: VbiCheckboxCustomEvent<HTMLVbiCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiCheckboxElement: {
        prototype: HTMLVbiCheckboxElement;
        new (): HTMLVbiCheckboxElement;
    };
    interface HTMLVbiConfigProviderElementEventMap {
        "vbiBuilderChange": VBIChartBuilder;
    }
    interface HTMLVbiConfigProviderElement extends Components.VbiConfigProvider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiConfigProviderElementEventMap>(type: K, listener: (this: HTMLVbiConfigProviderElement, ev: VbiConfigProviderCustomEvent<HTMLVbiConfigProviderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiConfigProviderElementEventMap>(type: K, listener: (this: HTMLVbiConfigProviderElement, ev: VbiConfigProviderCustomEvent<HTMLVbiConfigProviderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiConfigProviderElement: {
        prototype: HTMLVbiConfigProviderElement;
        new (): HTMLVbiConfigProviderElement;
    };
    interface HTMLVbiDropdownElementEventMap {
        "vbiDropdownToggle": boolean;
    }
    interface HTMLVbiDropdownElement extends Components.VbiDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiDropdownElementEventMap>(type: K, listener: (this: HTMLVbiDropdownElement, ev: VbiDropdownCustomEvent<HTMLVbiDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiDropdownElementEventMap>(type: K, listener: (this: HTMLVbiDropdownElement, ev: VbiDropdownCustomEvent<HTMLVbiDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiDropdownElement: {
        prototype: HTMLVbiDropdownElement;
        new (): HTMLVbiDropdownElement;
    };
    interface HTMLVbiIconElement extends Components.VbiIcon, HTMLStencilElement {
    }
    var HTMLVbiIconElement: {
        prototype: HTMLVbiIconElement;
        new (): HTMLVbiIconElement;
    };
    interface HTMLVbiInputElementEventMap {
        "vbiInputValue": string;
        "vbiInputChange": string;
        "vbiInputFocus": void;
        "vbiInputBlur": void;
    }
    interface HTMLVbiInputElement extends Components.VbiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiInputElementEventMap>(type: K, listener: (this: HTMLVbiInputElement, ev: VbiInputCustomEvent<HTMLVbiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiInputElementEventMap>(type: K, listener: (this: HTMLVbiInputElement, ev: VbiInputCustomEvent<HTMLVbiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiInputElement: {
        prototype: HTMLVbiInputElement;
        new (): HTMLVbiInputElement;
    };
    interface HTMLVbiJoinElement extends Components.VbiJoin, HTMLStencilElement {
    }
    var HTMLVbiJoinElement: {
        prototype: HTMLVbiJoinElement;
        new (): HTMLVbiJoinElement;
    };
    interface HTMLVbiLoadingElement extends Components.VbiLoading, HTMLStencilElement {
    }
    var HTMLVbiLoadingElement: {
        prototype: HTMLVbiLoadingElement;
        new (): HTMLVbiLoadingElement;
    };
    interface HTMLVbiMenuElementEventMap {
        "vbiMenuSelect": MenuItem;
    }
    interface HTMLVbiMenuElement extends Components.VbiMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiMenuElementEventMap>(type: K, listener: (this: HTMLVbiMenuElement, ev: VbiMenuCustomEvent<HTMLVbiMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiMenuElementEventMap>(type: K, listener: (this: HTMLVbiMenuElement, ev: VbiMenuCustomEvent<HTMLVbiMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiMenuElement: {
        prototype: HTMLVbiMenuElement;
        new (): HTMLVbiMenuElement;
    };
    interface HTMLVbiModalElementEventMap {
        "vbiModalToggle": boolean;
    }
    interface HTMLVbiModalElement extends Components.VbiModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiModalElementEventMap>(type: K, listener: (this: HTMLVbiModalElement, ev: VbiModalCustomEvent<HTMLVbiModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiModalElementEventMap>(type: K, listener: (this: HTMLVbiModalElement, ev: VbiModalCustomEvent<HTMLVbiModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiModalElement: {
        prototype: HTMLVbiModalElement;
        new (): HTMLVbiModalElement;
    };
    interface HTMLVbiSelectElementEventMap {
        "vbiSelectChange": string;
    }
    interface HTMLVbiSelectElement extends Components.VbiSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiSelectElementEventMap>(type: K, listener: (this: HTMLVbiSelectElement, ev: VbiSelectCustomEvent<HTMLVbiSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiSelectElementEventMap>(type: K, listener: (this: HTMLVbiSelectElement, ev: VbiSelectCustomEvent<HTMLVbiSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiSelectElement: {
        prototype: HTMLVbiSelectElement;
        new (): HTMLVbiSelectElement;
    };
    interface HTMLVbiSwitchElementEventMap {
        "vbiSwitchChange": boolean;
    }
    interface HTMLVbiSwitchElement extends Components.VbiSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiSwitchElementEventMap>(type: K, listener: (this: HTMLVbiSwitchElement, ev: VbiSwitchCustomEvent<HTMLVbiSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiSwitchElementEventMap>(type: K, listener: (this: HTMLVbiSwitchElement, ev: VbiSwitchCustomEvent<HTMLVbiSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiSwitchElement: {
        prototype: HTMLVbiSwitchElement;
        new (): HTMLVbiSwitchElement;
    };
    interface HTMLVbiTabElementEventMap {
        "vbiTabChange": TabItem;
    }
    interface HTMLVbiTabElement extends Components.VbiTab, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVbiTabElementEventMap>(type: K, listener: (this: HTMLVbiTabElement, ev: VbiTabCustomEvent<HTMLVbiTabElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVbiTabElementEventMap>(type: K, listener: (this: HTMLVbiTabElement, ev: VbiTabCustomEvent<HTMLVbiTabElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVbiTabElement: {
        prototype: HTMLVbiTabElement;
        new (): HTMLVbiTabElement;
    };
    interface HTMLVbiTooltipElement extends Components.VbiTooltip, HTMLStencilElement {
    }
    var HTMLVbiTooltipElement: {
        prototype: HTMLVbiTooltipElement;
        new (): HTMLVbiTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "vbi-button": HTMLVbiButtonElement;
        "vbi-cascading-menu": HTMLVbiCascadingMenuElement;
        "vbi-chart-dimension": HTMLVbiChartDimensionElement;
        "vbi-chart-editor": HTMLVbiChartEditorElement;
        "vbi-chart-field-filter": HTMLVbiChartFieldFilterElement;
        "vbi-chart-field-section": HTMLVbiChartFieldSectionElement;
        "vbi-chart-fields": HTMLVbiChartFieldsElement;
        "vbi-chart-having": HTMLVbiChartHavingElement;
        "vbi-chart-having-filter": HTMLVbiChartHavingFilterElement;
        "vbi-chart-measure": HTMLVbiChartMeasureElement;
        "vbi-chart-render": HTMLVbiChartRenderElement;
        "vbi-chart-shelf-panel": HTMLVbiChartShelfPanelElement;
        "vbi-chart-toolbar": HTMLVbiChartToolbarElement;
        "vbi-chart-type": HTMLVbiChartTypeElement;
        "vbi-chart-upload": HTMLVbiChartUploadElement;
        "vbi-chart-where": HTMLVbiChartWhereElement;
        "vbi-chart-where-filter": HTMLVbiChartWhereFilterElement;
        "vbi-checkbox": HTMLVbiCheckboxElement;
        "vbi-config-provider": HTMLVbiConfigProviderElement;
        "vbi-dropdown": HTMLVbiDropdownElement;
        "vbi-icon": HTMLVbiIconElement;
        "vbi-input": HTMLVbiInputElement;
        "vbi-join": HTMLVbiJoinElement;
        "vbi-loading": HTMLVbiLoadingElement;
        "vbi-menu": HTMLVbiMenuElement;
        "vbi-modal": HTMLVbiModalElement;
        "vbi-select": HTMLVbiSelectElement;
        "vbi-switch": HTMLVbiSwitchElement;
        "vbi-tab": HTMLVbiTabElement;
        "vbi-tooltip": HTMLVbiTooltipElement;
    }
}
declare namespace LocalJSX {
    interface VbiButton {
        /**
          * Active state (pressed/selected)
          * @default false
         */
        "active"?: boolean;
        /**
          * Main color (primary, secondary, accent, etc.)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Shape (square, circle, wide, block)
         */
        "shape"?: 'square' | 'circle' | 'wide' | 'block';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Type of the button
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant (ghost, outline, dash, soft, link)
         */
        "variant"?: 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
    }
    interface VbiCascadingMenu {
        /**
          * Array of menu items to be rendered
          * @default []
         */
        "items"?: CascadingMenuItem[];
        /**
          * Fired when a menu item is clicked
         */
        "onVbiCascadingMenuSelect"?: (event: VbiCascadingMenuCustomEvent<CascadingMenuItem>) => void;
        /**
          * The size of the menu. Defaults to 'md'
          * @default 'md'
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * The orientation variant of the menu. Defaults to 'vertical'
          * @default 'vertical'
         */
        "variant"?: 'horizontal' | 'vertical';
    }
    interface VbiChartDimension {
    }
    interface VbiChartEditor {
    }
    interface VbiChartFieldFilter {
        /**
          * The current search keyword.
          * @default ''
         */
        "keyword"?: string;
        /**
          * Emitted when the user changes the search keyword.
         */
        "onVbiChartFieldFilterKeyword"?: (event: VbiChartFieldFilterCustomEvent<string>) => void;
        /**
          * Emitted when the user changes the selected roles in the filter dropdown.
         */
        "onVbiChartFieldFilterRole"?: (event: VbiChartFieldFilterCustomEvent<FieldRole[]>) => void;
        /**
          * Emitted when the user changes the selected types in the filter dropdown.
         */
        "onVbiChartFieldFilterType"?: (event: VbiChartFieldFilterCustomEvent<string[]>) => void;
        /**
          * The currently selected field roles.
          * @default []
         */
        "selectedRoles"?: FieldRole[];
        /**
          * The currently selected field types.
          * @default []
         */
        "selectedTypes"?: string[];
    }
    interface VbiChartFieldSection {
        /**
          * The list of dimensions to display.
          * @default []
         */
        "dimensions"?: VBISchemaField[];
        /**
          * The list of measures to display.
          * @default []
         */
        "measures"?: VBISchemaField[];
    }
    interface VbiChartFields {
    }
    interface VbiChartHaving {
    }
    interface VbiChartHavingFilter {
        /**
          * @default {}
         */
        "fieldRoleMap"?: Record<string, string>;
        /**
          * @default {}
         */
        "fieldTypeMap"?: Record<string, string>;
        "item": HavingFilterLike;
        "onVbiChartHavingFilterCancel"?: (event: VbiChartHavingFilterCustomEvent<MouseEvent | undefined>) => void;
        "onVbiChartHavingFilterSave"?: (event: VbiChartHavingFilterCustomEvent<{ item: HavingFilterLike; event?: MouseEvent }>) => void;
    }
    interface VbiChartMeasure {
    }
    interface VbiChartRender {
        /**
          * The VSeed configuration object used to render the chart or table.
         */
        "vseed"?: VSeed;
    }
    interface VbiChartShelfPanel {
    }
    interface VbiChartToolbar {
    }
    interface VbiChartType {
    }
    interface VbiChartUpload {
        /**
          * Prefix for generated local CSV connector IDs.
          * @default 'local_csv'
         */
        "connectorIdPrefix"?: string;
        /**
          * Emitted when a CSV file is successfully uploaded and imported into the chart store.
         */
        "onVbiChartUploadSuccess"?: (event: VbiChartUploadCustomEvent<{
    connectorId: string
    fileName: string
    rowCount: number
  }>) => void;
    }
    interface VbiChartWhere {
    }
    interface VbiChartWhereFilter {
        /**
          * @default {}
         */
        "fieldRoleMap"?: Record<string, string>;
        /**
          * @default {}
         */
        "fieldTypeMap"?: Record<string, string>;
        "item": WhereFilterLike;
        "onVbiChartWhereFilterCancel"?: (event: VbiChartWhereFilterCustomEvent<MouseEvent | undefined>) => void;
        "onVbiChartWhereFilterSave"?: (event: VbiChartWhereFilterCustomEvent<{ item: WhereFilterLike; event?: MouseEvent }>) => void;
    }
    interface VbiCheckbox {
        /**
          * Whether the component is checked.
          * @default false
         */
        "checked"?: boolean;
        /**
          * The theme color of the component.
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Whether the component is disabled.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether the checkbox is in an indeterminate state.
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * The name of the component, used for form submission.
          * @default ''
         */
        "name"?: string;
        /**
          * Emitted when the checkbox value changes.
         */
        "onVbiCheckboxChange"?: (event: VbiCheckboxCustomEvent<boolean>) => void;
        /**
          * The size of the component.
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiConfigProvider {
        /**
          * VBI chart builder instance to initialize the store with
         */
        "builder"?: VBIChartBuilder;
        /**
          * Emitted when the builder is changed internally
         */
        "onVbiBuilderChange"?: (event: VbiConfigProviderCustomEvent<VBIChartBuilder>) => void;
        /**
          * Theme configuration containing mode ('light' | 'dark') and design tokens
         */
        "theme"?: ThemeConfig;
    }
    interface VbiDropdown {
        /**
          * When true, the dropdown cannot be opened.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The distance between the dropdown and its trigger (in pixels).
          * @default 8
         */
        "offset"?: number;
        /**
          * Emitted when the dropdown opens or closes.
         */
        "onVbiDropdownToggle"?: (event: VbiDropdownCustomEvent<boolean>) => void;
        /**
          * Controls the open state of the dropdown.
          * @default false
         */
        "open"?: boolean;
        /**
          * The position of the dropdown relative to its trigger.
          * @default 'bottom'
         */
        "placement"?: DropdownPlacement;
        /**
          * The interaction mode of the popover ('auto' closes on outside click, 'manual' does not).
          * @default 'auto'
         */
        "popoverMode"?: 'auto' | 'manual';
        /**
          * How the dropdown is triggered.
          * @default 'click'
         */
        "trigger"?: 'click' | 'hover';
    }
    interface VbiIcon {
        /**
          * The color of the icon. Defaults to 'currentColor'.
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * The icon definition object from `@ant-design/icons-svg`.
         */
        "icon"?: IconDefinition;
        /**
          * The size of the icon (unitless, scaled relative to --size-base).
          * @default 16
         */
        "size"?: number;
    }
    interface VbiInput {
        /**
          * Autocomplete hint for the browser
         */
        "autocomplete"?: string;
        /**
          * Auto-focus the input on mount
          * @default false
         */
        "autofocus"?: boolean;
        /**
          * Primary color (primary, secondary, info, error...)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Maximum value for number or date input
         */
        "max"?: number | string;
        /**
          * Maximum character length
         */
        "maxlength"?: number;
        /**
          * Minimum value for number or date input
         */
        "min"?: number | string;
        /**
          * Minimum character length
         */
        "minlength"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Event emitted when the input loses focus (blur)
         */
        "onVbiInputBlur"?: (event: VbiInputCustomEvent<void>) => void;
        /**
          * Event emitted when the user finishes typing and blurs (or presses Enter)
         */
        "onVbiInputChange"?: (event: VbiInputCustomEvent<string>) => void;
        /**
          * Event emitted when the input gains focus
         */
        "onVbiInputFocus"?: (event: VbiInputCustomEvent<void>) => void;
        /**
          * Event emitted when the user types
         */
        "onVbiInputValue"?: (event: VbiInputCustomEvent<string>) => void;
        /**
          * Placeholder text
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Read-only state (focusable but not editable)
          * @default false
         */
        "readOnly"?: boolean;
        /**
          * Required field for form validation
          * @default false
         */
        "required"?: boolean;
        /**
          * Size of the input
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Step for number input
         */
        "step"?: number | string;
        /**
          * Type of the input element (text, password, email, number, date...)
          * @default 'text'
         */
        "type"?: string;
        /**
          * Value of the input element
          * @default ''
         */
        "value"?: string | number;
        /**
          * Display variant (e.g., ghost - transparent)
         */
        "variant"?: 'ghost';
    }
    interface VbiJoin {
        /**
          * Vertical orientation
          * @default false
         */
        "vertical"?: boolean;
    }
    interface VbiLoading {
        /**
          * Primary color. If not provided, it inherits the parent element's text color (currentColor)
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Size (xs, sm, md, lg, xl)
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Loading style (spinner, dots, ring, ball, bars, infinity)
          * @default 'spinner'
         */
        "type"?: 'spinner' | 'dots' | 'ring' | 'ball' | 'bars' | 'infinity';
    }
    interface VbiMenu {
        /**
          * Array of menu items to be rendered
          * @default []
         */
        "items"?: MenuItem[];
        /**
          * Fired when a menu item is clicked
         */
        "onVbiMenuSelect"?: (event: VbiMenuCustomEvent<MenuItem>) => void;
        /**
          * The size of the menu. Defaults to 'md'
          * @default 'md'
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * The orientation variant of the menu. Defaults to 'vertical'
          * @default 'vertical'
         */
        "variant"?: 'horizontal' | 'vertical';
    }
    interface VbiModal {
        "onVbiModalToggle"?: (event: VbiModalCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'middle'
         */
        "position"?: 'top' | 'bottom' | 'middle' | 'start' | 'end';
    }
    interface VbiSelect {
        /**
          * Color variant of the select
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'success' | 'warning' | 'info' | 'error' | 'neutral' | 'ghost';
        /**
          * Whether the select is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the user changes the selected option
         */
        "onVbiSelectChange"?: (event: VbiSelectCustomEvent<string>) => void;
        /**
          * List of select options
         */
        "options"?: SelectOption[];
        /**
          * Placeholder text when no option is selected
         */
        "placeholder"?: string;
        /**
          * Size of the select
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Current value of the select
         */
        "value"?: string | number;
    }
    interface VbiSwitch {
        /**
          * Whether the switch is checked.
          * @default false
         */
        "checked"?: boolean;
        /**
          * The color theme of the switch.
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'success' | 'warning' | 'info' | 'error' | 'neutral';
        /**
          * Whether the switch is disabled.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The name of the component, used for form submission.
          * @default ''
         */
        "name"?: string;
        /**
          * Emitted when the switch checked state changes.
         */
        "onVbiSwitchChange"?: (event: VbiSwitchCustomEvent<boolean>) => void;
        /**
          * The size of the switch.
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiTab {
        /**
          * Whether the tabs occupy the full width of their parent container
          * @default false
         */
        "block"?: boolean;
        /**
          * Whether all tabs are disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Array of tab items to be rendered
          * @default []
         */
        "items"?: TabItem[];
        /**
          * Emitted when a tab item is clicked
         */
        "onVbiTabChange"?: (event: VbiTabCustomEvent<TabItem>) => void;
        /**
          * Size of the tabs
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * Currently active tab value or ID
         */
        "value"?: string | number;
    }
    interface VbiTooltip {
        /**
          * The semantic color theme of the tooltip
         */
        "color"?: 'primary' | 'secondary' | 'accent' | 'info' | 'success' | 'warning' | 'error';
        /**
          * Delay in milliseconds before showing the tooltip on hover
          * @default 0
         */
        "enterDelay"?: number;
        /**
          * Delay in milliseconds before hiding the tooltip on leave
          * @default 0
         */
        "leaveDelay"?: number;
        /**
          * The distance between the tooltip and its trigger (in pixels)
          * @default 8
         */
        "offset"?: number;
        /**
          * Whether the tooltip is currently open/visible
          * @default false
         */
        "open"?: boolean;
        /**
          * The position of the tooltip relative to its target
          * @default 'top'
         */
        "position"?: TooltipPosition;
        /**
          * The text to display inside the tooltip
          * @default ''
         */
        "text"?: string;
        /**
          * How the tooltip is triggered ('hover', 'click', or 'manual')
          * @default 'hover'
         */
        "trigger"?: 'hover' | 'click' | 'manual';
    }

    interface VbiButtonAttributes {
        "type": 'button' | 'submit' | 'reset';
        "color": 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        "variant": 'ghost' | 'outline' | 'dash' | 'soft' | 'link';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "shape": 'square' | 'circle' | 'wide' | 'block';
        "disabled": boolean;
        "active": boolean;
    }
    interface VbiCascadingMenuAttributes {
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "variant": 'horizontal' | 'vertical';
    }
    interface VbiChartFieldFilterAttributes {
        "keyword": string;
    }
    interface VbiChartUploadAttributes {
        "connectorIdPrefix": string;
    }
    interface VbiCheckboxAttributes {
        "checked": boolean;
        "indeterminate": boolean;
        "disabled": boolean;
        "name": string;
        "color": 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiDropdownAttributes {
        "placement": DropdownPlacement;
        "popoverMode": 'auto' | 'manual';
        "trigger": 'click' | 'hover';
        "offset": number;
        "disabled": boolean;
        "open": boolean;
    }
    interface VbiIconAttributes {
        "size": number;
        "color": string;
    }
    interface VbiInputAttributes {
        "type": string;
        "value": string;
        "placeholder": string;
        "disabled": boolean;
        "name": string;
        "readOnly": boolean;
        "required": boolean;
        "maxlength": number;
        "minlength": number;
        "min": string;
        "max": string;
        "step": string;
        "autocomplete": string;
        "autofocus": boolean;
        "color": 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
        "variant": 'ghost';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiJoinAttributes {
        "vertical": boolean;
    }
    interface VbiLoadingAttributes {
        "type": 'spinner' | 'dots' | 'ring' | 'ball' | 'bars' | 'infinity';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "color": 'primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error';
    }
    interface VbiMenuAttributes {
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "variant": 'horizontal' | 'vertical';
    }
    interface VbiModalAttributes {
        "open": boolean;
        "position": 'top' | 'bottom' | 'middle' | 'start' | 'end';
    }
    interface VbiSelectAttributes {
        "value": string;
        "placeholder": string;
        "disabled": boolean;
        "color": 'primary' | 'secondary' | 'accent' | 'success' | 'warning' | 'info' | 'error' | 'neutral' | 'ghost';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiSwitchAttributes {
        "checked": boolean;
        "disabled": boolean;
        "name": string;
        "color": 'primary' | 'secondary' | 'accent' | 'success' | 'warning' | 'info' | 'error' | 'neutral';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface VbiTabAttributes {
        "value": string;
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "disabled": boolean;
        "block": boolean;
    }
    interface VbiTooltipAttributes {
        "text": string;
        "position": TooltipPosition;
        "color": 'primary' | 'secondary' | 'accent' | 'info' | 'success' | 'warning' | 'error';
        "open": boolean;
        "offset": number;
        "trigger": 'hover' | 'click' | 'manual';
        "enterDelay": number;
        "leaveDelay": number;
    }

    interface IntrinsicElements {
        "vbi-button": Omit<VbiButton, keyof VbiButtonAttributes> & { [K in keyof VbiButton & keyof VbiButtonAttributes]?: VbiButton[K] } & { [K in keyof VbiButton & keyof VbiButtonAttributes as `attr:${K}`]?: VbiButtonAttributes[K] } & { [K in keyof VbiButton & keyof VbiButtonAttributes as `prop:${K}`]?: VbiButton[K] };
        "vbi-cascading-menu": Omit<VbiCascadingMenu, keyof VbiCascadingMenuAttributes> & { [K in keyof VbiCascadingMenu & keyof VbiCascadingMenuAttributes]?: VbiCascadingMenu[K] } & { [K in keyof VbiCascadingMenu & keyof VbiCascadingMenuAttributes as `attr:${K}`]?: VbiCascadingMenuAttributes[K] } & { [K in keyof VbiCascadingMenu & keyof VbiCascadingMenuAttributes as `prop:${K}`]?: VbiCascadingMenu[K] };
        "vbi-chart-dimension": VbiChartDimension;
        "vbi-chart-editor": VbiChartEditor;
        "vbi-chart-field-filter": Omit<VbiChartFieldFilter, keyof VbiChartFieldFilterAttributes> & { [K in keyof VbiChartFieldFilter & keyof VbiChartFieldFilterAttributes]?: VbiChartFieldFilter[K] } & { [K in keyof VbiChartFieldFilter & keyof VbiChartFieldFilterAttributes as `attr:${K}`]?: VbiChartFieldFilterAttributes[K] } & { [K in keyof VbiChartFieldFilter & keyof VbiChartFieldFilterAttributes as `prop:${K}`]?: VbiChartFieldFilter[K] };
        "vbi-chart-field-section": VbiChartFieldSection;
        "vbi-chart-fields": VbiChartFields;
        "vbi-chart-having": VbiChartHaving;
        "vbi-chart-having-filter": VbiChartHavingFilter;
        "vbi-chart-measure": VbiChartMeasure;
        "vbi-chart-render": VbiChartRender;
        "vbi-chart-shelf-panel": VbiChartShelfPanel;
        "vbi-chart-toolbar": VbiChartToolbar;
        "vbi-chart-type": VbiChartType;
        "vbi-chart-upload": Omit<VbiChartUpload, keyof VbiChartUploadAttributes> & { [K in keyof VbiChartUpload & keyof VbiChartUploadAttributes]?: VbiChartUpload[K] } & { [K in keyof VbiChartUpload & keyof VbiChartUploadAttributes as `attr:${K}`]?: VbiChartUploadAttributes[K] } & { [K in keyof VbiChartUpload & keyof VbiChartUploadAttributes as `prop:${K}`]?: VbiChartUpload[K] };
        "vbi-chart-where": VbiChartWhere;
        "vbi-chart-where-filter": VbiChartWhereFilter;
        "vbi-checkbox": Omit<VbiCheckbox, keyof VbiCheckboxAttributes> & { [K in keyof VbiCheckbox & keyof VbiCheckboxAttributes]?: VbiCheckbox[K] } & { [K in keyof VbiCheckbox & keyof VbiCheckboxAttributes as `attr:${K}`]?: VbiCheckboxAttributes[K] } & { [K in keyof VbiCheckbox & keyof VbiCheckboxAttributes as `prop:${K}`]?: VbiCheckbox[K] };
        "vbi-config-provider": VbiConfigProvider;
        "vbi-dropdown": Omit<VbiDropdown, keyof VbiDropdownAttributes> & { [K in keyof VbiDropdown & keyof VbiDropdownAttributes]?: VbiDropdown[K] } & { [K in keyof VbiDropdown & keyof VbiDropdownAttributes as `attr:${K}`]?: VbiDropdownAttributes[K] } & { [K in keyof VbiDropdown & keyof VbiDropdownAttributes as `prop:${K}`]?: VbiDropdown[K] };
        "vbi-icon": Omit<VbiIcon, keyof VbiIconAttributes> & { [K in keyof VbiIcon & keyof VbiIconAttributes]?: VbiIcon[K] } & { [K in keyof VbiIcon & keyof VbiIconAttributes as `attr:${K}`]?: VbiIconAttributes[K] } & { [K in keyof VbiIcon & keyof VbiIconAttributes as `prop:${K}`]?: VbiIcon[K] };
        "vbi-input": Omit<VbiInput, keyof VbiInputAttributes> & { [K in keyof VbiInput & keyof VbiInputAttributes]?: VbiInput[K] } & { [K in keyof VbiInput & keyof VbiInputAttributes as `attr:${K}`]?: VbiInputAttributes[K] } & { [K in keyof VbiInput & keyof VbiInputAttributes as `prop:${K}`]?: VbiInput[K] };
        "vbi-join": Omit<VbiJoin, keyof VbiJoinAttributes> & { [K in keyof VbiJoin & keyof VbiJoinAttributes]?: VbiJoin[K] } & { [K in keyof VbiJoin & keyof VbiJoinAttributes as `attr:${K}`]?: VbiJoinAttributes[K] } & { [K in keyof VbiJoin & keyof VbiJoinAttributes as `prop:${K}`]?: VbiJoin[K] };
        "vbi-loading": Omit<VbiLoading, keyof VbiLoadingAttributes> & { [K in keyof VbiLoading & keyof VbiLoadingAttributes]?: VbiLoading[K] } & { [K in keyof VbiLoading & keyof VbiLoadingAttributes as `attr:${K}`]?: VbiLoadingAttributes[K] } & { [K in keyof VbiLoading & keyof VbiLoadingAttributes as `prop:${K}`]?: VbiLoading[K] };
        "vbi-menu": Omit<VbiMenu, keyof VbiMenuAttributes> & { [K in keyof VbiMenu & keyof VbiMenuAttributes]?: VbiMenu[K] } & { [K in keyof VbiMenu & keyof VbiMenuAttributes as `attr:${K}`]?: VbiMenuAttributes[K] } & { [K in keyof VbiMenu & keyof VbiMenuAttributes as `prop:${K}`]?: VbiMenu[K] };
        "vbi-modal": Omit<VbiModal, keyof VbiModalAttributes> & { [K in keyof VbiModal & keyof VbiModalAttributes]?: VbiModal[K] } & { [K in keyof VbiModal & keyof VbiModalAttributes as `attr:${K}`]?: VbiModalAttributes[K] } & { [K in keyof VbiModal & keyof VbiModalAttributes as `prop:${K}`]?: VbiModal[K] };
        "vbi-select": Omit<VbiSelect, keyof VbiSelectAttributes> & { [K in keyof VbiSelect & keyof VbiSelectAttributes]?: VbiSelect[K] } & { [K in keyof VbiSelect & keyof VbiSelectAttributes as `attr:${K}`]?: VbiSelectAttributes[K] } & { [K in keyof VbiSelect & keyof VbiSelectAttributes as `prop:${K}`]?: VbiSelect[K] };
        "vbi-switch": Omit<VbiSwitch, keyof VbiSwitchAttributes> & { [K in keyof VbiSwitch & keyof VbiSwitchAttributes]?: VbiSwitch[K] } & { [K in keyof VbiSwitch & keyof VbiSwitchAttributes as `attr:${K}`]?: VbiSwitchAttributes[K] } & { [K in keyof VbiSwitch & keyof VbiSwitchAttributes as `prop:${K}`]?: VbiSwitch[K] };
        "vbi-tab": Omit<VbiTab, keyof VbiTabAttributes> & { [K in keyof VbiTab & keyof VbiTabAttributes]?: VbiTab[K] } & { [K in keyof VbiTab & keyof VbiTabAttributes as `attr:${K}`]?: VbiTabAttributes[K] } & { [K in keyof VbiTab & keyof VbiTabAttributes as `prop:${K}`]?: VbiTab[K] };
        "vbi-tooltip": Omit<VbiTooltip, keyof VbiTooltipAttributes> & { [K in keyof VbiTooltip & keyof VbiTooltipAttributes]?: VbiTooltip[K] } & { [K in keyof VbiTooltip & keyof VbiTooltipAttributes as `attr:${K}`]?: VbiTooltipAttributes[K] } & { [K in keyof VbiTooltip & keyof VbiTooltipAttributes as `prop:${K}`]?: VbiTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vbi-button": LocalJSX.IntrinsicElements["vbi-button"] & JSXBase.HTMLAttributes<HTMLVbiButtonElement>;
            "vbi-cascading-menu": LocalJSX.IntrinsicElements["vbi-cascading-menu"] & JSXBase.HTMLAttributes<HTMLVbiCascadingMenuElement>;
            "vbi-chart-dimension": LocalJSX.IntrinsicElements["vbi-chart-dimension"] & JSXBase.HTMLAttributes<HTMLVbiChartDimensionElement>;
            "vbi-chart-editor": LocalJSX.IntrinsicElements["vbi-chart-editor"] & JSXBase.HTMLAttributes<HTMLVbiChartEditorElement>;
            "vbi-chart-field-filter": LocalJSX.IntrinsicElements["vbi-chart-field-filter"] & JSXBase.HTMLAttributes<HTMLVbiChartFieldFilterElement>;
            "vbi-chart-field-section": LocalJSX.IntrinsicElements["vbi-chart-field-section"] & JSXBase.HTMLAttributes<HTMLVbiChartFieldSectionElement>;
            "vbi-chart-fields": LocalJSX.IntrinsicElements["vbi-chart-fields"] & JSXBase.HTMLAttributes<HTMLVbiChartFieldsElement>;
            "vbi-chart-having": LocalJSX.IntrinsicElements["vbi-chart-having"] & JSXBase.HTMLAttributes<HTMLVbiChartHavingElement>;
            "vbi-chart-having-filter": LocalJSX.IntrinsicElements["vbi-chart-having-filter"] & JSXBase.HTMLAttributes<HTMLVbiChartHavingFilterElement>;
            "vbi-chart-measure": LocalJSX.IntrinsicElements["vbi-chart-measure"] & JSXBase.HTMLAttributes<HTMLVbiChartMeasureElement>;
            "vbi-chart-render": LocalJSX.IntrinsicElements["vbi-chart-render"] & JSXBase.HTMLAttributes<HTMLVbiChartRenderElement>;
            "vbi-chart-shelf-panel": LocalJSX.IntrinsicElements["vbi-chart-shelf-panel"] & JSXBase.HTMLAttributes<HTMLVbiChartShelfPanelElement>;
            "vbi-chart-toolbar": LocalJSX.IntrinsicElements["vbi-chart-toolbar"] & JSXBase.HTMLAttributes<HTMLVbiChartToolbarElement>;
            "vbi-chart-type": LocalJSX.IntrinsicElements["vbi-chart-type"] & JSXBase.HTMLAttributes<HTMLVbiChartTypeElement>;
            "vbi-chart-upload": LocalJSX.IntrinsicElements["vbi-chart-upload"] & JSXBase.HTMLAttributes<HTMLVbiChartUploadElement>;
            "vbi-chart-where": LocalJSX.IntrinsicElements["vbi-chart-where"] & JSXBase.HTMLAttributes<HTMLVbiChartWhereElement>;
            "vbi-chart-where-filter": LocalJSX.IntrinsicElements["vbi-chart-where-filter"] & JSXBase.HTMLAttributes<HTMLVbiChartWhereFilterElement>;
            "vbi-checkbox": LocalJSX.IntrinsicElements["vbi-checkbox"] & JSXBase.HTMLAttributes<HTMLVbiCheckboxElement>;
            "vbi-config-provider": LocalJSX.IntrinsicElements["vbi-config-provider"] & JSXBase.HTMLAttributes<HTMLVbiConfigProviderElement>;
            "vbi-dropdown": LocalJSX.IntrinsicElements["vbi-dropdown"] & JSXBase.HTMLAttributes<HTMLVbiDropdownElement>;
            "vbi-icon": LocalJSX.IntrinsicElements["vbi-icon"] & JSXBase.HTMLAttributes<HTMLVbiIconElement>;
            "vbi-input": LocalJSX.IntrinsicElements["vbi-input"] & JSXBase.HTMLAttributes<HTMLVbiInputElement>;
            "vbi-join": LocalJSX.IntrinsicElements["vbi-join"] & JSXBase.HTMLAttributes<HTMLVbiJoinElement>;
            "vbi-loading": LocalJSX.IntrinsicElements["vbi-loading"] & JSXBase.HTMLAttributes<HTMLVbiLoadingElement>;
            "vbi-menu": LocalJSX.IntrinsicElements["vbi-menu"] & JSXBase.HTMLAttributes<HTMLVbiMenuElement>;
            "vbi-modal": LocalJSX.IntrinsicElements["vbi-modal"] & JSXBase.HTMLAttributes<HTMLVbiModalElement>;
            "vbi-select": LocalJSX.IntrinsicElements["vbi-select"] & JSXBase.HTMLAttributes<HTMLVbiSelectElement>;
            "vbi-switch": LocalJSX.IntrinsicElements["vbi-switch"] & JSXBase.HTMLAttributes<HTMLVbiSwitchElement>;
            "vbi-tab": LocalJSX.IntrinsicElements["vbi-tab"] & JSXBase.HTMLAttributes<HTMLVbiTabElement>;
            "vbi-tooltip": LocalJSX.IntrinsicElements["vbi-tooltip"] & JSXBase.HTMLAttributes<HTMLVbiTooltipElement>;
        }
    }
}
